# Generated by Django 6.0.6 on 2026-06-12 09:40

from datetime import date, timedelta

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.utils import timezone


def seed_lot(apps, feedyard, quantity, entry_date, average_weight):
    Lot = apps.get_model("api", "Lot")
    Animal = apps.get_model("api", "Animal")
    WeightRecord = apps.get_model("api", "WeightRecord")

    lot = Lot.objects.create(
        feedyard=feedyard,
        name=f"Lote {entry_date.strftime('%d-%m-%Y')}",
    )
    animals = [
        Animal(
            lot=lot,
            entry_date=entry_date,
            initial_weight=average_weight,
            current_weight=average_weight,
        )
        for _ in range(quantity)
    ]
    Animal.objects.bulk_create(animals, batch_size=5000)

    days = (timezone.localdate() - entry_date).days
    dates = [entry_date + timedelta(days=d) for d in range(days + 1)]
    WeightRecord.objects.bulk_create(
        [
            WeightRecord(animal_id=a.pk, weight=average_weight, date=d)
            for a in animals
            for d in dates
        ],
        batch_size=5000,
    )


def seed_data(apps, schema_editor):
    Feedyard = apps.get_model("api", "Feedyard")
    User = apps.get_model("api", "User")
    Token = apps.get_model("authtoken", "Token")

    feedyard_norte = Feedyard.objects.create(name="Feedyard Norte")
    feedyard_sur = Feedyard.objects.create(name="Feedyard Sur")

    user_norte = User.objects.create(
        username="norte",
        password=make_password("pass"),
        feedyard=feedyard_norte,
        language="es",
    )
    user_sur = User.objects.create(
        username="sur",
        password=make_password("pass"),
        feedyard=feedyard_sur,
        language="en",
    )
    Token.objects.create(user=user_norte, key="token-norte")
    Token.objects.create(user=user_sur, key="token-sur")

    seed_lot(
        apps,
        feedyard=feedyard_norte,
        quantity=10,
        entry_date=date(2026, 5, 1),
        average_weight=320.0,
    )
    seed_lot(
        apps,
        feedyard=feedyard_norte,
        quantity=5,
        entry_date=date(2026, 5, 15),
        average_weight=280.0,
    )
    seed_lot(
        apps,
        feedyard=feedyard_sur,
        quantity=8,
        entry_date=date(2026, 4, 20),
        average_weight=350.0,
    )
    seed_lot(
        apps,
        feedyard=feedyard_sur,
        quantity=12,
        entry_date=date(2026, 6, 1),
        average_weight=310.0,
    )


def unseed_data(apps, schema_editor):
    User = apps.get_model("api", "User")
    Feedyard = apps.get_model("api", "Feedyard")

    User.objects.filter(username__in=["norte", "sur"]).delete()
    Feedyard.objects.filter(name__in=["Feedyard Norte", "Feedyard Sur"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        ("authtoken", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]
